# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            shiv.me
tagline:          musings, rants, raves, and occasional burts of awesome!
url:              http://shiv.me
paginate:         10
baseurl:          /
author:
  name:           Shiva
  url:            https://twitter.com/shiva
  email:          shiv@shiv.me

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole


pages_list:       
    About: '/about'
    Archive: '/archive'
    Feed: '/atom.xml'
