name:           shiv.me
markdown:       kramdown
highlighter:    rouge
permalink:      :year/:month/:title

github: https://github.com/shiva/shiva.github.io
urls:
    - text: about
      url: /about
    - text: github
      url: https://github.com/shiva
    - text: email
      url: mailto:shiv@shiv.me

tagline:        musings, rants, raves, and occasional bursts of awesome!
url:            http://blog.shiv.me
paginate:       5
baseurl:        ""

#pages_list:       
#    About: '/about'
#    Archive: '/archive'
#    Feed: '/atom.xml'

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"

jekyll-crosspost_to_medium:
    enabled: true 
    cache: .jekyll-crosspost_to_medium
    status: draft
    license: cc-40-by-nc-sa

gems:
    - jekyll-paginate
      #- jekyll-crosspost_to_medium
