# Dependencies
markdown:        kramdown 
highlighter:     rouge

# Permalinks
permalink:        :year/:month/:title

# Setup
title:            shiv.me
tagline:          musings, rants, raves, and occasional bursts of awesome!
#url:              http://blog.shiv.me
baseurl:          ""
paginate:         5
author:
  name:           Shiva
  url:            https://twitter.com/shiva
  email:          shiv@shiv.me

# Custom vars
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  social:
    github: shiva
    bitbucket: shiva
    goodreads: shiv
    #hacker_news: swanson
    #stackexchange: 348619
    #stackoverflow: 348619
    twitter: shiva
    facebook: shivanand
    tumblr: shiva
    linkedin: vshivanand
    flickr: shvelmur
    500px: shiv
    #gplus: 110552447039675960964

  lsi: false
  show_disclaimer: true

version:          1.0.0
github:
  repo:           https://github.com/shiva/shiva.github.io

#pages_list:       
#    About: '/about'
#    Projects: '/projects'
#    Archive: '/archive'

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

jekyll-crosspost_to_medium:
    enabled: true 
    cache: .jekyll-crosspost_to_medium
    status: draft
    license: cc-40-by-nc-sa

picture:
      source: "images"
      output: "generated"
      markup: "picture"
      presets:
          default:
              ppi: [1, 1.5]
              source_large:
                  media: "(min-width: 800px)"
                  width: "800"
              source_medium:
                  media: "(min-width: 600px)"
                  width: "600"
              source_default: 
                  width: "300"

gems:
    - jekyll-paginate
    - jekyll-crosspost-to-medium
    - jekyll-picture-tag

