# Dependencies
markdown:         kramdown
highlighter:      true

# Permalinks
permalink:        :year/:month/:title

# Setup
title:            shiv.me
tagline:          musings, rants, raves, and occasional bursts of awesome!
url:              "http://blog.shiv.me"
paginate:         10
baseurl:          ""
author:
  name:           Shiva
  url:            https://twitter.com/shiva
  email:          shiv@shiv.me

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/shiva/shiva.github.io

pages_list:       
    About: '/about'
    Archive: '/archive'
    Feed: '/atom.xml'

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

gems: [jekyll-paginate]


jekyll-crosspost_to_medium:
    enabled: true 
    cache: .jekyll-crosspost_to_medium
    status: draft
    license: cc-40-by-nc-sa

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: 

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false
